# Generated by Django 4.1 on 2023-02-06 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=30)),
                ('club_description', models.TextField()),
                ('club_location', models.CharField(max_length=30)),
                ('club_url', models.URLField()),
                ('club_genre', models.CharField(max_length=30)),
                ('club_picture', models.ImageField(blank=True, default='club_pictures/default_club.png', upload_to='club_pictures')),
                ('eighteen_plus', models.BooleanField(default=False)),
                ('average_club_rating', models.FloatField(blank=True, default=0.0)),
                ('club_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('picture', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pictures')),
                ('bio', models.CharField(blank=True, max_length=100)),
                ('is_club_owner', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('clubs_subscibed', models.ManyToManyField(blank=True, to='profiles.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
