# Generated by Django 4.1 on 2023-03-13 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_sex_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_genre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
